island_permission: "skyblocks.command.island"
look_island_permission: "skyblocks.command.look_island"
touch_island_permission: "skyblocks.touch_island"
auto_save_internal: 1200 # 20 * 60 = 1200 = 60 seconds