island_permission: "skyblocks.command.island"
look_island_permission: "skyblocks.command.look_island"
touch_island_permission: "skyblocks.touch_island"
auto_save_internal: 1200 # 20 * 60 = 1200 = 60 seconds

# Available providers: json, mongo, mysql, sqlite
provider: "json"

mongo.uri: "mongodb://localhost:27017/"
mongo.database: "database"

mysql:
  url: "jdbc:mysql://localhost:3306/database"
  user: "root"
  password: "password"

chest_contents:
  - "81:0:3"
  - "295:0:3"
  - "361:0:3"
  - "362:0:3"
  - "458:0:3"
  - "79:0:2"
  - "325:10:1"
  - "297:0:16"

